# Generated by Django 5.2.14 on 2026-06-02 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "در انتظار پرداخت"),
                            ("confirmed", "تأیید شده"),
                            ("cancelled", "لغو شده"),
                            ("completed", "انجام شده"),
                            ("no_show", "غیبت"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["pending_payment", "confirmed"])
                        ),
                        fields=("doctor", "date", "start_time"),
                        name="unique_active_appointment_slot",
                    )
                ],
            },
        ),
    ]
