# Generated by Django 4.2.16 on 2026-06-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_add_provider_avatar'),
        ('appointments', '0002_refactor_multitenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت\u200cها'},
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_busines_fc8df3_idx',
            old_name='apt_business_date_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_busines_154213_idx',
            old_name='apt_business_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_provide_4e8bd5_idx',
            old_name='apt_provider_date_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_custome_48801d_idx',
            old_name='apt_customer_status_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='موبایل مشتری'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='providers.provider', verbose_name='ارائه\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tracking_code',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tracking_code'], name='appointment_trackin_e79ccf_idx'),
        ),
    ]
