# Generated by Django 4.2.16 on 2026-06-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_add_provider_avatar'),
        ('providers', '0004_drop_old_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='provider_avatars/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='businesses.business', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('medical', 'پزشکی و سلامت'), ('beauty', 'آرایشگاه و زیبایی'), ('legal', 'وکالت و مشاوره حقوقی'), ('financial', 'مشاوره مالی'), ('psychological', 'روانشناسی و مشاوره'), ('fitness', 'ورزش و تناسب\u200cاندام'), ('education', 'آموزش و تدریس'), ('veterinary', 'دامپزشکی'), ('automotive', 'تعمیرگاه و خودرو'), ('other', 'سایر')], default='other', max_length=30, verbose_name='دسته\u200cبندی'),
        ),
    ]
