# Generated by Django 4.2.16 on 2026-06-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_add_provider_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='مدت (دقیقه)')),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_services',
                'ordering': ['name'],
            },
        ),
    ]
