# Generated by Django 5.2.14 on 2026-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="phone",
            field=models.CharField(max_length=11),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                condition=models.Q(("is_used", False)),
                fields=["phone", "expires_at"],
                name="otp_active_phone_expires_idx",
            ),
        ),
    ]
