# Generated by Django 4.2.16 on 2026-06-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_provide_7e1517_idx',
            old_name='reviews_provider_created_idx',
        ),
    ]
