# Generated by Django 4.2.16 on 2026-06-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_add_provider_avatar'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='service',
            new_name='services_busines_302365_idx',
            old_name='service_business_active_idx',
        ),
        migrations.RenameIndex(
            model_name='timeoff',
            new_name='timeoffs_provide_ad4434_idx',
            old_name='timeoff_provider_date_idx',
        ),
        migrations.RenameIndex(
            model_name='timeoff',
            new_name='timeoffs_busines_de9d1c_idx',
            old_name='timeoff_business_date_idx',
        ),
        migrations.RenameIndex(
            model_name='workinghours',
            new_name='working_hou_provide_b122ec_idx',
            old_name='wh_provider_weekday_idx',
        ),
        migrations.RenameIndex(
            model_name='workinghours',
            new_name='working_hou_busines_ad9f57_idx',
            old_name='wh_business_weekday_idx',
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider', verbose_name='ارائه\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='service',
            name='buffer_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='زمان آماده\u200cسازی بین دو نوبت متوالی', verbose_name='فاصله بعد از نوبت (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='خالی = تعطیلی کل کسب\u200cوکار', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeoffs', to='providers.provider', verbose_name='ارائه\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='start_time',
            field=models.TimeField(blank=True, help_text='خالی = تمام روز', null=True, verbose_name='از ساعت'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='خالی = ساعت پیش\u200cفرض کسب\u200cوکار', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='providers.provider', verbose_name='ارائه\u200cدهنده'),
        ),
    ]
