# Generated by Django 4.2.16 on 2026-06-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_latin_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='business',
            name='businesses_latin_s_3ad52d_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='branches_busines_1f8734_idx',
            old_name='branch_business_active_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='businesses_slug_279d6a_idx',
            old_name='businesses_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='businesses_owner_i_77f58e_idx',
            old_name='businesses_owner_active_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='businesses_categor_f571c3_idx',
            old_name='businesses_category_active_idx',
        ),
        migrations.RenameIndex(
            model_name='businessmember',
            new_name='business_me_user_id_bebcf4_idx',
            old_name='bm_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='businessmember',
            new_name='business_me_busines_ac5e74_idx',
            old_name='bm_business_role_idx',
        ),
        migrations.RenameIndex(
            model_name='businessmember',
            new_name='business_me_busines_6792bb_idx',
            old_name='bm_business_active_idx',
        ),
        migrations.AlterField(
            model_name='business',
            name='latin_slug',
            field=models.SlugField(blank=True, help_text='آدرس اختصاصی انگلیسی صفحه رزرو: nobatic.ir/book/{latin_slug}', max_length=80, null=True, unique=True, verbose_name='آدرس اختصاصی (لاتین)'),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='آدرس صفحه رزرو: nobatic.ir/book/{slug}', max_length=100, unique=True, verbose_name='شناسه URL'),
        ),
    ]
